#!/bin/bash
echo -e "\e[1m\e[48;5;219m\e[38;5;232m ♥ THE LOVE GENERATOR ♥ \e[0m"
echo -e "\e[38;5;219mTell me your name <3\e[0m"
read name1
echo -e "\e[38;5;219mTell me the name of the other person ;)\e[0m"
read name2
echo -e "\e[95mThe love percent of $name1 and $name2 is
♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥\e[0m"
echo -e "\e[1m\e[48;5;219m\e[38;5;232m (｡♥‿♥｡)  $(( RANDOM % 100 ))%  (｡♥‿♥｡) \e[0m"
